### PR TITLE
Remove freemarker.

### PR DESCRIPTION
**Pull request by yogurtearl**
Fixes https://github.com/Karumi/Shot/issues/231

### :pushpin: References
* **Issue:** #231

### :tophat: What is the goal?

Fixes  gradle config cache issue caused by freemarker. 

### How is it being implemented?

Remove Freemarker and just use Scala String interpolation. 

### How can it be tested?

Behavior should not change other than fixing the config cache warning when using this plugin.

### CODE REVIEW

**Comment by chrisjenx** [comment]
Cool, was freemarker used for anything else, or was it just that template?

**Comment by yogurtearl** [comment]
Yeah, best I can tell, it was only used for 2 fairly simple templates, easily replaced by scala string interpolation.

**Comment by chrisjenx** [comment]
Awesome, less deps is always good too. Nice work!

**Comment by pedrovgs** [comment]
Hey @yogurtearl thank you so much for your contribution :smiley: Before reviewing the code I've noticed there was an error in the code formatting I've fixed and pushed to your branch. 

Next week I'll take a look at the code. If everything is ok, I'll release a new version with the fix!

**Review by pedrovgs — APPROVED** [review]
Well done @yogurtearl 👍

**Pull request merged**
