### PR TITLE
Use Task Provider to avoid task creation during configuration

### PR DESCRIPTION
**Pull request by chrisjenx**
### :pushpin: References
- Noticed shot was creating tasks during configuration

### :tophat: What is the goal?

This changes task lookup to lazy, via `named` meaning tasks won't be created during configuration.

Screen Shot 2021-07-03 at 2 47 29 PM

### How can it be tested?

- During configuration shot should have no "tasks" next to it, that means they are created when requested instead of during configuration.
- Should work the exact same way as before, all tasks match what was previously generated.

### CODE REVIEW

**Comment by chrisjenx** [comment]
@yogurtearl wondering if this looks good to you too?

**Comment by yogurtearl** [comment]
LGTM

**Comment by inktomi** [comment]
I suspect that this PR will solve a compatibility issue that I'm seeing with AGP 7.0.0 about something querying `applicationId` during configuration time. I've tracked that down to Shot, and I bet this PR would solve that.

**Comment by chrisjenx** [comment]
Ah yes we were seeing that to. Thanks for the quick fix

**Comment by chrisjenx** [comment]
Oh wait this is my pr lol, oh because right now it's not a lazy look up?

**Comment by pedrovgs** [comment]
Thank you so much guys. You rock 😃  I'm going to release a new version with the fix right now.

Please @inktomi could you check if the release fixes the issue with AGP 7.0.0 and the appId param?

**Comment by chrisjenx** [comment]
Unfortunatlly looks like this didn't fix it for us. Lemme have a look later today.

**Comment by inktomi** [comment]
Yea, there still seems to be something going on - sorry, I should have built the project and tested before my comment.

**Comment by yogurtearl** [comment]
> Unfortunatlly looks like this didn't fix it for us. 

didn't fix the task creation during config? or didn't fix AGP 7.0.0 compatibility?

**Comment by chrisjenx** [comment]
> > Unfortunately looks like this didn't fix it for us.
> 
> didn't fix the task creation during config? or didn't fix AGP 7.0.0 compatibility?

The latter

**Pull request merged**
