### PR TITLE
Updated compose version to alpha12

### PR DESCRIPTION
**Pull request by Stuart-campbell**
### :tophat: What is the goal?

Updated compose version to lastest alpha. (alpha12), Also added a requires android O annotation to resolve a lint error following on from what had been done for another function

### How is it being implemented?

N/A

### How can it be tested?

Ran all the units tests seemed fine although I did expect to have to update the kotlin version to 1.4.30 but seemed happy with the current version.

### CODE REVIEW

**Comment by pedrovgs** [comment]
@Stuart-campbell thank you so much for your contribution 😃 Could you please update the consumer project to use the new compose version too? Thank you in advance 😃

**Comment by Stuart-campbell** [comment]
> @Stuart-campbell thank you so much for your contribution 😃 Could you please update the consumer project to use the new compose version too? Thank you in advance 😃

Guess this is out of date already with beta-01 out today 😃

**Comment by pedrovgs** [comment]
Not really. We can release two versions. One providing support for alpha 12 and another one providing support for beta1.

**Comment by Stuart-campbell** [comment]
> Not really. We can release two versions. One providing support for alpha 12 and another one providing support for beta1.

Sounds good, once this is merged I would be happy to follow up with another for beta01. 👍

**Review by pedrovgs — APPROVED** [review]
Great thanks!

**Comment by pedrovgs** [comment]
Thanks @Stuart-campbell 😃  I'm going to migrate to beta 1 today, so don't worry.

**Pull request merged**
