### PR TITLE
Update build dependencies + Use task configuration avoidance api

### PR DESCRIPTION
**Pull request by mateuszkwiecinski**
### :pushpin: References
* **Issue:** continuation of #208
* **Related pull-requests:** #208

### :tophat: What is the goal?
To make the plugin development more efficient. Current master downloads some artifacts on each build: https://scans.gradle.com/s/ddbtrcbte5vi4/performance/network-activity
Which gets quickly annoying.

### How is it being implemented?
I updated most of plugin dependencies which solved the issue described above. 
I also switched to lazy configuration api, both for plugin build and for the plugin itself. 

https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

|current config| this PR|
|---|---|
|image|image|

Wroth reviewing by commits as updting scalafmt dependency caused a lot of automatically generated changes. I'll try to comment out each unobvious change

### How can it be tested?
There should be no behavior changes except more efficient build.

- [ ] **Use case 1:** _A brief description of the use case that should be tested_
- [ ] **Use case 2:** _If the use case requires some complex steps, increase indentation_
  - [ ] _Step 1_
  - [ ] _Step 2_

### CODE REVIEW

**Comment by mateuszkwiecinski** [comment]
@pedrovgs Sure, no rush. I know there is a lot of changes at once. Please let me know if you prefer to split them into multiple PRs. I assumed that reviewing one build-related PR will be easier and quicker for you

**Comment by mateuszkwiecinski** [comment]
> It adds no value and only adds noise for this PR

The `scalafmt` plugin is actually responsible for downloading the artifact I mentioned, visible in: https://scans.gradle.com/s/ddbtrcbte5vi4/performance/network-activity. 

But sure, I'll split these changes into 2 separate PRs

**Comment by pedrovgs** [comment]
Thanks!

**Comment by pedrovgs** [comment]
@mateuszkwiecinski I've just merged the scala fmt PR. Is this still a draft? Do you need to rebase to make github aware you've updated this branch so we can see an updated diff?

**Comment by mateuszkwiecinski** [comment]
@pedrovgs yes, I waited for #217 to be merged first. I just rebased this PR and it should be ready for review 👀

**Review by pedrovgs — APPROVED** [review]

**Comment by pedrovgs** [comment]
Thanks for your help @mateuszkwiecinski 😃

**Pull request merged**
