### PR TITLE
Update facebook dependency to 0.8.0

### PR DESCRIPTION
**Pull request by diegolucasb**
### :pushpin: References
* **Issue:** #42 

### :tophat: What is the goal?
* To increment facebook screenshot testing library to 0.8.0
* To upgrade android support library to 28

### How is it being implemented?
* Increase facebook library version to 0.8.0
* Increase android support library to 28

### How can it be tested?
* Start a new emulator
* Run './gradlew executeScreenshotTests -Precord'
* Run './gradlew executeScreenshotTests' 
And check if everything works properly

### CODE REVIEW

**Comment by Serchinastico** [comment]
Nevermind! I was able to push my changes to your branch! I'm waiting for CI to pass and will merge your branch. Thank you again for your contribution!

**Comment by diegolucasb** [comment]
Hi @Serchinastico, I’m happy to help and I'm glad you were able to make the changes.

I saw Bitrise is still broken but I'm not able to see the logs.
If you need me to change anything, just let me know!

**Comment by pedrovgs** [comment]
I don't know what's going on with bitrise. So I'm merging this branch and I'll take a look later at the build configuration so we don't block the release.

**Comment by pedrovgs** [comment]
@Serchinastico @diegolucasb I've just released a new version of the library. Thank you so much for your time and contributions to this repository 👏

**Comment by diegolucasb** [comment]
My pleasure!

**Pull request merged**
